// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnArEJhaI3vj6jdlHskq5uHm28rzvPlh4',
    appId: '1:607407824489:web:252a449964cdda444e4cf8',
    messagingSenderId: '607407824489',
    projectId: 'betterme-18761',
    authDomain: 'betterme-18761.firebaseapp.com',
    storageBucket: 'betterme-18761.firebasestorage.app',
    measurementId: 'G-CWM16LSK4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrscn-JRZ9tIQ5JY5g1omRg1XyRFDdq88',
    appId: '1:607407824489:android:160000d4325a7e854e4cf8',
    messagingSenderId: '607407824489',
    projectId: 'betterme-18761',
    storageBucket: 'betterme-18761.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUm7Enb9RyMl0VXMq6n34uLHDJMVxD2Uk',
    appId: '1:607407824489:ios:e2ea5c792f0f98d54e4cf8',
    messagingSenderId: '607407824489',
    projectId: 'betterme-18761',
    storageBucket: 'betterme-18761.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUm7Enb9RyMl0VXMq6n34uLHDJMVxD2Uk',
    appId: '1:607407824489:ios:e2ea5c792f0f98d54e4cf8',
    messagingSenderId: '607407824489',
    projectId: 'betterme-18761',
    storageBucket: 'betterme-18761.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnArEJhaI3vj6jdlHskq5uHm28rzvPlh4',
    appId: '1:607407824489:web:a11b70dd0e6bf4384e4cf8',
    messagingSenderId: '607407824489',
    projectId: 'betterme-18761',
    authDomain: 'betterme-18761.firebaseapp.com',
    storageBucket: 'betterme-18761.firebasestorage.app',
    measurementId: 'G-YEKJXVLZFV',
  );
}
